REM   Script: Weather Analysis Using SQL
REM   


CREATE TABLE STATION 
( 
ID NUMBER, 
CITY CHAR(20), 
STATE CHAR(2), 
LAT_N NUMBER, 
LONG_N NUMBER 
);

ALTER TABLE STATION MODIFY LONG_N TO LONG_W NUMBER 
;

ALTER TABLE STATION MODIFY LONG_N AS LONG_W NUMBER 
;

ALTER TABLE STATION MODIFY LONG_N IN LONG_W NUMBER 
;

INSERT INTO STATION VALUES (13,'PHOENIX','AZ',33,112);

INSERT INTO STATION VALUES (44,'DENVER','CO',40,105);

INSERT INTO STATION VALUES (66,'CARIBU','ME',47,68);

ALTER TABLE RENAME LONG_N AS LONG_W 
;

ALTER TABLE STATION RENAME LONG_N AS LONG_W 
;

RENAME STATION LONG_N AS LONG_W 



ALTER TABLE STATION RENAME COLUMN LONG_N TO LONG_W;

SELECT LAT_N FROM STATION WHERE LAT_N> 39.7;

CREATE TABLE STATS 
( 
ID NUMBER, 
MONTH NUMBER, 
TEMP_F NUMBER, 
RAIN_I NUMBER 
);

INSERT INTO STATION VALUES (13,1,57.4,0.31);

INSERT INTO STATION VALUES (13, 7, 91.7, 5.15);

INSERT INTO STATION VALUES (44, 1, 27.3, 0.18);

INSERT INTO STATION VALUES (44, 7, 74.8, 2.11);

INSERT INTO STATION VALUES (66, 1, 6.7, 2.1);

INSERT INTO STATION VALUES (66, 7, 65.8, 4.52);

INSERT INTO STATS VALUES (13, 1 ,57.4,0.31);

INSERT INTO STATS VALUES (13, 7, 91.7, 5.15);

INSERT INTO STATS VALUES (44, 1, 27.3, 0.18);

INSERT INTO STATS VALUES (44, 7, 74.8, 2.11);

INSERT INTO STATS VALUES (66, 1, 6.7, 2.1);

INSERT INTO STATS VALUES (66, 7, 65.8, 4.52);

SELECT TEMP,CITY FROM STATS, STATION WHERE STATION.ID=STATS.ID;

SELECT TEMP_F,CITY FROM STATS, STATION WHERE STATION.ID=STATS.ID;

SELECT CITY, TEMP_F FROM STATION, STATS WHERE STATION.ID=STATS.ID;

SELECT MONTH,RAIN_I,CITY FROM STATS S,STATION ST WHERE S.ID=ST.ID ORDER BY MONTH DESC;

SELECT MONTH,RAIN_I,CITY FROM STATS S,STATION ST WHERE S.ID=ST.ID ORDER BY MONTH ASC ORDER BY RAIN_I DESC;

SELECT MONTH,RAIN_I,CITY FROM STATS S,STATION ST WHERE S.ID=ST.ID GROUP BY MONTH ORDER BY RAIN_I DESC;

GROUP BY MONTH


SELECT MONTH,RAIN_I,CITY FROM STATS S,STATION ST WHERE S.ID=ST.ID ORDER BY RAIN_I;

SELECT *,CITY FROM STATS S,STATION ST WHERE S.ID=ST.ID ORDER BY RAIN_I DESC;

SELECT ID,MONTH,RAIN_I,TEMP_F,CITY FROM STATS S,STATION ST WHERE S.ID=ST.ID ORDER BY RAIN_I DESC;

SELECT MONTH,RAIN_I,TEMP_F,CITY FROM STATS S,STATION ST WHERE S.ID=ST.ID ORDER BY RAIN_I DESC;

SELECT MONTH,RAIN_I,CITY FROM STATS S,STATION ST WHERE S.ID=ST.ID ORDER BY RAIN_I DESC;

SELECT CITY, MONTH,RAIN_I, FROM STATION ST,STATS S WHERE S.ID=ST.ID ORDER BY RAIN_I DESC;

SELECT CITY, MONTH,RAIN_I FROM STATION ST,STATS S WHERE S.ID=ST.ID ORDER BY RAIN_I DESC;

SELECT CITY,TEMP_F FROM STATS, STATION WHERE STATS.ID=STATION.ID AND WHERE MONTH=7;

SELECT CITY,TEMP_F FROM STATS, STATION WHERE STATS.ID=STATION.ID AND WHERE MONTH=7 GROUP BY MONTH;

SELECT TEMP, CITY FROM STATION,STATS WHERE STATION.ID=STATS.ID AND WHERE STATS.MONTH=7;

SELECT CITY,TEMP_F FROM STATION S, STATS T WHERE S.ID=T.ID AND T.MONTH =7;

SELECT CITY,TEMP_F FROM STATION S, STATS T WHERE S.ID=T.ID AND T.MONTH =7 ORDER BY TEMP_F;

SELECT CITY,MAX(TEMP_F),MIN(TEMP_F),AVG(TEMP_F) FROM STATION S, STATS T WHERE S.ID=T.ID GROUP BY CITY;

8.SELECT CITY, MONTH,RAIN_I FROM STATION ST,STATS S WHERE S.ID=ST.ID ORDER BY MONTH,RAIN_I DESC;


SELECT * FROM STATS S INNER JOIN STATION T ON S.ID=T.ID  ORDER BY MONTH, RAIN_I DESC;

SELECT * FROM STATS S JOIN STATION T ON S.ID=T.ID  ORDER BY MONTH, RAIN_I DESC;

SELECT * FROM STATS S NATURAL JOIN STATION T ON S.ID=T.ID  ORDER BY MONTH, RAIN_I DESC;

SELECT * FROM STATS S  
INNER JOIN STATION T  
ON S.ID=T.ID   
ORDER BY MONTH, RAIN_I DESC;

SELECT ID,CITY,MONTH 
ROUND(TEMP_F-32)*5/9) AS TEMP_CELCIUS 
ROUND(RAIN_I*0.3937) AS RAIN_CENTIMERTER 
FROM STATIONS S, STATS T WHERE S.ID=T.ID;

SELECT ID,CITY,MONTH 
ROUND((TEMP_F-32)*5/9) AS TEMPERATURE_CELCIUS 
ROUND(RAIN_I*0.3937) AS RAINFALL_CENT 
FROM STATION S 
JOIN STATS T 
ON S.ID=T.ID;

SELECT ID,CITY,MONTH, 
ROUND((TEMP-32)*5/9,2) AS TEMP_CELCIUS 
ROUND(RAIN*0.393701, 2) AS RAIN_CENT 
FROM STATIONS S 
JOIN STATS T 
ON S.ID=T.ID;

SELECT S.ID,S.CITY,T.MONTH, 
ROUND((TEMP-32)*5/9,2) AS TEMP_CELCIUS, 
ROUND(RAIN*0.393701, 2) AS RAIN_CENT 
FROM STATIONS S 
JOIN STATS T 
ON S.ID=T.ID;

SELECT S.ID,S.CITY,T.MONTH, 
ROUND((TEMP-32)*5/9,2) AS TEMP_CELCIUS, 
ROUND(RAIN*0.393701, 2) AS RAIN_CENT 
FROM STATION S 
JOIN STATS T 
ON S.ID=T.ID 
;

SELECT S.ID,S.CITY,T.MONTH, 
ROUND((TEMP-32)*5/9,2) AS TEMP_CELCIUS, 
ROUND(RAIN*0.393701, 2) AS RAIN_CENT 
FROM STATION S 
JOIN STATS T 
ON S.ID=T.ID;

SELECT * FROM STATION 
;

SELECT S.ID, S.City,  
T.MONTH, 
ROUND((TEMP_F - 32) * 5 /9) As TEMP_CELCIUS,  
Round(RAIN_I * 0.3937) As RAINFALL_CENTIMETER 
From STATS T 
JOIN STATION S 
ON S.ID = T.ID ;

SELECT S.ID, S.CITY,T.MONTH, ROUND((TEMP_F - 32)*5/9,2) AS TEMP_CELCIUS, 
ROUND(RAIN_I *0.393701) AS RAIN_CENT 
FROM STATION S 
JOIN STATS T 
JOIN STATION S 
ON S.ID = T.ID;

SELECT S.ID, S.CITY,T.MONTH, ROUND((TEMP_F - 32)*5/9,2) AS TEMP_CELCIUS, 
ROUND(RAIN_I *0.393701) AS RAIN_CENT 
FROM STATION S 
JOIN STATS T 
ON S.ID = T.ID;

SELECT S.ID, S.CITY,T.MONTH, 
ROUND((TEMP_F - 32)*5/9,2) AS TEMP_CELCIUS, 
ROUND(RAIN_I *0.393701) AS RAIN_CENT 
FROM STATION S 
JOIN STATS T 
ON S.ID = T.ID 
ORDER BY MONTH;

UPDATE STATS SET RAIN_I = RAIN_I +0.01;

UPDATE STATS SET TEMP_F =74.9 WHERE CITY ='DENVER' AND MONTH =7;

UPDATE STATS SET TEMP_F =74.9 WHERE (SELECT CITY FROM STATION)='DENVER' AND MONTH =7;

UPDATE STATS SET TEMP_F =74.9 WHERE IN (SELECT CITY FROM STATION)='DENVER' AND MONTH =7;

UPDATE STATS SET TEMP_F =74.9 WHERE CITY = (SELECT CITY FROM STATION WHERE CITY='DENVER') AND MONTH =7;

UPDATE STATS SET TEMP_F =74.9 WHERE STATION.CITY = (SELECT CITY FROM STATION WHERE CITY='DENVER') AND MONTH =7;

UPDATE STATS SET TEMP_F =74.9 WHERE ID=(SELECT CITY FROM STATION WHERE CITY= 'DENVER') AND MONTH =7;

UPDATE STATS SET TEMP_F =74.9 WHERE ID=(SELECT ID FROM STATION WHERE CITY= 'DENVER') AND MONTH =7;

SELECT * FROM STATS 
;

SELECT CITY, TEMP_F FROM STATION, STATS  
WHERE STATION.ID=STATS.ID;

SELECT * FROM STATION WHERE LAT_N> 39.7;

SELECT T.ID,S.MONTH,S.CITY,T.TEMP_F,T.RAIN_I  
FROM STATS S  
INNER JOIN STATION T  
ON S.ID=T.ID   
ORDER BY MONTH, RAIN_I DESC;

SELECT T.ID,S.MONTH,S.CITY,T.TEMP_F,T.RAIN_I 
FROM STATIONS 
JOIN STATS 
ON T.ID=S.ID;

SELECT T.ID,S.MONTH,S.CITY,T.TEMP_F,T.RAIN_I 
FROM STATIONS S 
JOIN STATS T 
ON T.ID=S.ID;

SELECT T.ID,S.MONTH,S.CITY,T.TEMP_F,T.RAIN_I 
FROM STATIONS AS S 
JOIN STATS AS T 
ON T.ID=S.ID;

SELECT S.MONTH, S.CITY, T.ID, T.TEMP_F, T.RAIN_I 
FROM STATS T INNER JOIN STATIONS S 
ON S.ID= T.ID;

SELECT * FROM STATS;

SELECT * FROM STATS INNER JOIN STATION ON STATS.ID = STATION.ID;

SELECT ID, MONTH, CITY, TEMP_F , RAIN_IFROM STATS INNER JOIN STATION ON STATS.ID = STATION.ID;

SELECT ID, MONTH, CITY, TEMP_F , RAIN_I FROM STATS INNER JOIN STATION ON STATS.ID = STATION.ID;

SELECT T.ID, T.MONTH, S.CITY, T.TEMP_F , T.RAIN_I FROM STATS T INNER JOIN STATION S ON STATS.ID = STATION.ID;

SELECT T.ID, T.MONTH, S.CITY, T.TEMP_F , T.RAIN_I FROM STATS T INNER JOIN STATION S ON T.ID = S.ID;

SELECT CITY,TEMP_F FROM STATION S, STATS T 
WHERE S.ID=T.ID AND T.MONTH =7  
ORDER BY TEMP_F;

SELECT CITY,TEMP_F, RAIN_I FROM STATION S, STATS T 
WHERE S.ID=T.ID AND T.MONTH =7  
ORDER BY TEMP_F;

SELECT CITY,LAT_N,TEMP_F, FROM STATION S, STATS T 
WHERE S.ID=T.ID AND T.MONTH =7  
ORDER BY TEMP_F;

SELECT * FROM STATION;

SELECT CITY, LAT_N, TEMP_F FROM STATION S, STATS T WHERE S.ID= T.ID;

SELECT CITY, LAT_N, TEMP_F FROM STATION S, STATS T  
WHERE S.ID= T.ID 
ORDER BY TEMP_F;

CREATE TABLE STATION 
( 
ID NUMBER, 
CITY CHAR(20), 
STATE CHAR(2), 
LAT_N NUMBER, 
LONG_W NUMBER, 
PRIMARY KEY(ID) 
);

